### ISSUE TITLE
How to setup or run program and what is id pass because it rejects user4 and test123

### ISSUE THREAD

**Issue by NaheelSalman** [sazanrjb/InventoryManagementSystem#5]
@sazanrjb dude you wrote very clean code i saw your source code appreciable 
now my question is that how could i run the software as you provide the link of just running software locally
when ever i run and put username user4 and password test123 it says invalid id pass
and when i run in eclipse it give me mysql error i tried so much but i could not trouble shoot it 
i will be thankful if you tell me process

**Comment by NaheelSalman** [comment]
i had also setup external jars (libraries) successfully 
and also run the MySQL server without any database
but i can't make connection with both of these or can run the software

**Comment by sajxraj** [comment]
So have you created a database called ims and imported the sql file I
provided?

**Comment by ibevictory** [comment]
Could you make maybe a youtube video or a video and upload it to cloud and put the link cause I'm also having problems in running it.

**Comment by NaheelSalman** [comment]
@sazanrjb yeah i have succesfully setup mysql local server with your script but its still connecting and giving invalid
user and pass
user4 , Test123
![asd](https://user-images.githubusercontent.com/39267623/98087810-774cf700-1ea2-11eb-867f-d50b0a299a89.JPG)
![dd](https://user-images.githubusercontent.com/39267623/98087928-a2374b00-1ea2-11eb-94fb-8e548b7ee08c.JPG)

**Comment by sajxraj** [comment]
password should have small t i.e. test123

Also make sure your mysql username and password is reflected on
ConnectionFactory class

**Comment by NaheelSalman** [comment]
Dude i have search for the error log :
`at java.sql.SQLException: Unable to load authentication plugin 'caching_sha2_password'.`
and i find solution from here which is working :
[Stack Over Flow Link](https://stackoverflow.com/questions/50387952/how-to-resolve-unable-to-load-authentication-plugin-caching-sha2-password-issu)
and i downloaded the newest version of jbdc mysql connector from here [MYSQL JAVA CONNECTOR 8.0 ](https://jar-download.com/download-handling.php)
and now i can connect with mysql server 
But the bad part of this whole thing is that still i can't log in to the program and even no more error logs in terminal 
Just error on screen of invalid user or pass
I have tried with test123 and Test123 both but still can't login 
if you have working software in your own local machine please share some snaps
