### ISSUE TITLE
Documentation requires Scribd account.

### ISSUE THREAD

**Issue by heyJonBray** [sazanrjb/InventoryManagementSystem#6]
Would you be able to move the documentation into the repo, or host it somewhere else?

I'm only able to read the first few pages before being prompted to sign up for scribd, and it cuts off before the introduction is finished.

**Comment by sajxraj** [comment]
@heyJonBray README updated. Here is the link: [Inventory-Management-System-Sajan-Rajbhandari.pdf](https://github.com/sazanrjb/InventoryManagementSystem/blob/master/docs/Inventory-Management-System-Sajan-Rajbhandari.pdf)
